/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cart: typeof import('./components/Cart.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    ProductDetails: typeof import('./components/ProductDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    Shop: typeof import('./components/Shop.vue')['default']
  }
}
